export const occupations = [
  { value: "house_wife", label: "House Wife" },
  { value: "job", label: "Job" },
  { value: "student", label: "Student" },
  { value: "retired", label: "Retired" },
  { value: "other", label: "Other" },
];

export const interests: Record<string, string[]> = {
  house_wife: [
    "Cooking",
    "Family",
    "Religion",
    "TV Dramas",
    "Books",
    "YouTube",
    "TikTok",
    "Gardening",
    "Shopping",
  ],
  job: [
    "News",
    "Business",
    "Sports",
    "Health",
    "Technology",
    "Travel",
    "Music",
    "TV",
  ],
  student: [
    "Studies",
    "Friends",
    "Sports",
    "Social",
    "Music",
    "Careers",
    "TV",
    "Creative",
  ],
  retired: [
    "Religion",
    "Family",
    "Health",
    "Gardening",
    "Reading",
    "Community",
    "TV",
    "Travel",
  ],
  other: [
    "Cooking",
    "Arts",
    "Books",
    "Music",
    "Travel",
    "Relaxation",
    "Shopping",
    "Social",
  ],
};
